task123/collegeproject/collegeproject/urls.py
from django.contrib import admin
from django.urls import path,include
from collegeproject import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('collegestore.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task123/collegeproject/collegestore/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('add/',views.form_add,name='form_add'),
    path('ajax/load-Course/',views.load_Course, name='ajax_load_Course'),
    path('new_page',views.new_page ,name='new_page'),
    path('formend',views.formend,name="formend")
]

task123/collegeproject/collegestore/models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Material(models.Model):
    debit_notebook=models.BooleanField(default=False)
    pen=models.BooleanField(default=False)
    exam_papers=models.BooleanField(default=False)


    def __str__(self):
        return self.name




class Purpose(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name
class Realform(models.Model):
    name=models.CharField(max_length=30)
    Dob=models.DateField(max_length=40)
    AGE=models.IntegerField()
    GENDER=models.CharField(max_length=13)
    PHONE_NUMBER=models.CharField(max_length=12)
    EMAIL=models.EmailField()
    ADDRESS=models.TextField(max_length=200)
    department=models.ForeignKey(Department, on_delete=models.SET_NULL,blank=True,null=True)
    course=models.ForeignKey(Course, on_delete=models.SET_NULL,blank=True,null=True)
    purpose=models.ForeignKey(Purpose, on_delete=models.CASCADE)
    debit_notebook = models.BooleanField(default=False)
    pen = models.BooleanField(default=False)
    exam_papers = models.BooleanField(default=False)

    def __str__(self):
        return self.name

task123/collegeproject/collegestore/forms.py
from django import forms
from .models import Realform, Course



class MyForm(forms.ModelForm):
    class Meta:
        model = Realform
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).all()
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.all()

task123/collegeproject/collegestore/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import MyForm
from .models import  Course

def home(request):
    return render(request,'Home.html')

def form_add(request):
    form = MyForm()
    if request.method == 'POST':
        form = MyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('formend')
    return render(request, 'main_form.html', {'form': form})


# AJAX
def load_Course(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).all()
    return render(request, 'Course_dropdown.html', {'courses': courses})
     # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def formend(request):
    return render(request,"formend.html")
def new_page(request):
    return render(request,"new_page.html")





def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"name already exist")
                return redirect("register")
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save()
                return  redirect("login")

        else:
            messages.info(request,"password not matching")
            return redirect("register")
    return render(request,'register.html')
def logout(request):
    auth.logout(request)
    return redirect('/')
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('new_page')
        else:
            messages.info(request,"invalid credentials")
            return redirect('login')
    return render(request,"login.html")

task123/collegeproject/templates/Course_dropdown.html
{% load static %}
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

task123/collegeproject/templates/Home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="menu-bar">
<ul>
    <li ><a href="login">login</a></li>
    <li ><a href="#">department</a>
    <div class="sub-menu-1">
        <ul>
         <li><a href="https://en.wikipedia.org/wiki/Science">science</a></li>
         <li><a href="https://en.wikipedia.org/wiki/commerce">commerce</a></li>
         <li><a href="https://en.wikipedia.org/wiki/arts">arts</a></li>
         <li><a href="https://en.wikipedia.org/wiki/politics">politics</a></li>
         <li><a href="https://en.wikipedia.org/wiki/sports">sports</a></li>
        </ul>
    </div>
    </li>
    <li><a href="register">register</a></li>
</ul>
    </div>
{% block content %}
{% endblock %}
</body>
</html>

task123/collegeproject/templates/formend.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2 style="text-align:center"> order is placed</h2>
<button><a href="logout" style="text-align:center">logout</a></button>
</body>
</html>

task123/collegeproject/templates/login.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<div class="login-container" style="font-family:arial;
    font-size:24px;
    margin:100px;
    width:350px;
    height:200px;
    position:relative;">
    <div class="login-main" style="height:50px;
                    width:50px;
                    position:absolute;
                    top:50%;
                    left:50%;
                    margin:-25px 0 0 -25px;">
     <form action="login" method="post">
         {% csrf_token %}
       <input type="text" name="username" placeholder="enter your username"><br>
         <input type="password" name="password" placeholder="enter your password"><br>
          <input type="submit" value="submit" >
     </form>
        {% for msg in messages %}
           {{msg}}
        {% endfor %}
        <li><a href="register">register_link</a></li>
    </div>
</div>
</body>
</html>
{% endblock %}

task123/collegeproject/templates/main_form.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
<h2>Person Form</h2>

<form method="post" id="personForm"  data-Course-url="{% url 'ajax_load_Course' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<script src="{% static 'jquery/min.js' %}"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#personForm").attr("data-Course-url");  // get the url of the `load_courses` view
        const departmentId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'department_id': departmentId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                 console.log(data);
                $("#id_course").html(data);   // replace the contents of the city input with the data that came from the server


                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_Course").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>


   

task123/collegeproject/templates/new_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new_page</title>
</head>
<body>
<button><a href="{% url 'form_add' %}" >real_form</a></button>
</body>
</html>

task123/collegeproject/templates/register.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
<div class="reg-container" style="font-family:arial;
    font-size:24px;
    margin:100px;
    width:350px;
    height:200px;
    position:relative;
">
    <div class="reg-menu" style="height:50px;
                    width:50px;
                    position:absolute;
                    top:50%;
                    left:50%;
                    margin:-25px 0 0 -25px;">
        <form action="register" method="post">
                {% csrf_token %}
             <input type="text" name="username" placeholder="enter your username"><br>
                <input type="password" name="password" placeholder="enter your password"><br>
                <input type="password" name="password1" placeholder="confirm password"><br>
                <button><input type="submit"></button>
         </form>
        {% for msg in messages %}
            {{msg}}
        {% endfor %}
    </div>
</div>

</body>
</html>
{% endblock %}